### ISSUE TITLE
Could not grab groups using the roles property

### ISSUE THREAD

**Issue by Neneil94** [kuoruan/verdaccio-openid#1]
Hello guys,
I want to implement this library with AzureAD openid endpoint.
I got everything setup correctly and also tested my AzureAD by using https://openidconnect.net/ (an OpenID Connect Playground).

While testing I could see that I get my `roles` from the user token. The problem now is that in verdaccio I get the following error message:
**Could not grab groups using the roles property**

This is my config `auth` part (anonymized):
```yaml
  auth:
    #htpasswd:
      # Do not change this path if secrets htpasswd is used.
      #file: /verdaccio/storage/htpasswd
      # Maximum amount of users allowed to register, defaults to "+infinity".
      # You can set this to -1 to disable registration.
      #max_users: 1000
    openid:
      provider-host: https://login.microsoftonline.com/bf8.../v2.0
      configuration-uri: https://login.microsoftonline.com/bf8.../v2.0/.well-known/openid-configuration
      #issuer: https://login.microsoftonline.com/bf8.../v2.0
      #authorization-endpoint: https://login.microsoftonline.com/bf8.../oauth2/v2.0/authorize
      #token-endpoint: https://login.microsoftonline.com/bf8.../oauth2/v2.0/token
      #userinfo-endpoint: https://graph.microsoft.com/oidc/userinfo
      #jwks-uri: https://login.microsoftonline.com/bf8.../discovery/v2.0/keys
      client-id: 67...
      client-secret: bN...
      username-claim: name
      scope: openid profile email
      groups-claim: roles
      authorized-group: true
```

This is my decrypted user token (`id_token`) I have anonymized the values:
```json
{
 "aud": "67...",
 "iss": "https://login.microsoftonline.com/bf8.../v2.0",
 "iat": 16...,
 "nbf": 16...,
 "exp": 16...,
 "aio": "AW...",
 "email": "my.email@example.com",
 "name": "myname",
 "oid": "0...",
 "preferred_username": "my.email@example.com",
 "rh": "0.A....",
 "roles": [
  "access",
  "publish"
 ],
 "sub": "Qki...",
 "tid": "bf...,
 "uti": "fw...",
 "ver": "2.0"
}
```

I've also checked your source code. I found out that the `getGroups` Method in `AuthProvider.ts` tries to get all `userinfo` by token what is not working for roles i guess. 

Also interesting, the `username-claim` in the `config.yaml` can access `name` but not `preferred_username`

In my tests with https://openidconnect.net/ I tested the exact same scope.
I've also tried to configure all endpoints manually, what is I thinks so not necessary when using the well-known endpoint.

I hope it is just a miss-configuration but since I've tried out everything I am not sure anymore.

Thankful for help.
