### ISSUE TITLE
yup validation fails for url when using redis protocol handler

### ISSUE THREAD

**Issue by MartinLoeper** [kuoruan/verdaccio-openid#10]
The following schema validation fails when using a url starting with "redis://". I think there is a set of accepted protocol handlers like "https" and "redis" is not one of them.

https://github.com/kuoruan/verdaccio-openid/pull/9/files#diff-3caf05e77d904e717131aaa201a3cef584ab93f99d12b5b56750bab7f307771cR244

Example that fails:
```yaml
auth:
  openid:
    store-type: redis
    store-config: "redis://verdaccio-redis-master.verdaccio:6379/"
```
