### ISSUE TITLE
[HELP] Integration with Authentik

### ISSUE THREAD

**Issue by jd-apprentice** [kuoruan/verdaccio-openid#6]
Hihi!

I'm trying to integrate verdaccio via openid connect with your plugin. I've tried to read the source code, but I can't understand why is going to one path or the other at this point.

Here is some information

```dockerfile
FROM verdaccio/verdaccio:6
ADD config/config.yaml /verdaccio/conf/config.yaml
USER root
RUN npm install --global verdaccio-static-token \
  && npm install --global verdaccio-auth-memory \
  && npm install --global verdaccio-openid

USER $VERDACCIO_USER_UID
```

Compose file

```yml
services:
  verdaccio-desa:
    build: .
    container_name: verdaccio-desa
    env_file:
      - .env
    ports:
      - '4873:4873'
    volumes:
      - './storage:/verdaccio/storage'
      - './config:/verdaccio/conf'
      - './plugins:/verdaccio/plugins'
    networks:
      - node-network-desa

networks:
  node-network-desa:
    driver: bridge
```

Config

```yml
storage: /verdaccio/storage
max_body_size: 100mb

web:
  enable: true
  title: ...
  gravatar: true
  sort_packages: asc

security:
  legacy: false
  api:
    jwt:
      sign:
        expiresIn: 30d
        notBefore: 0
  web:
    sign:
      expiresIn: 7d
      notBefore: 1

middlewares:
  openid:
    enabled: true

auth:
  openid:
    provider-host: ... 
    configuration-uri: .../.well-known/openid-configuration
    client-id: ...
    client-secret: ...
    username-claim: preferred_username
    groups-claim: groups

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

...packages

log:
  - { type: stdout, format: pretty-timestamped, level: trace }

listen:
  - 0.0.0.0:4873
```

```shell
docker compose logs
verdaccio-desa  | info --- config file  - /verdaccio/conf/config.yaml
verdaccio-desa  | info --- plugin loading: verdaccio-openid@0.11.1
verdaccio-desa  | info --- plugin successfully loaded: verdaccio-openid
verdaccio-desa  | info --- plugin loading: verdaccio-openid@0.11.1
verdaccio-desa  | info --- plugin successfully loaded: verdaccio-openid
verdaccio-desa  | warn --- http address - http://0.0.0.0:4873/ - verdaccio/6.0.1
verdaccio-desa  | error--- Could not discover client: outgoing request timed out after 3500ms
verdaccio-desa  | error--- Could not discover client: outgoing request timed out after 3500ms
```

Whenever I click on the login button, I receive the following

```shell
verdaccio-desa  | info <-- ... requested 'GET /-/oauth/authorize'
verdaccio-desa  | error--- auth error: Client has not yet been discovered
verdaccio-desa  | error--- unexpected error: Client has not yet been discovered
verdaccio-desa  | ReferenceError: Client has not yet been discovered
verdaccio-desa  |     at get discoveredClient [as discoveredClient] (/usr/local/lib/node_modules/verdaccio-openid/dist/server/index.js:385:13)
verdaccio-desa  |     at OpenIDConnectAuthProvider.getLoginUrl (/usr/local/lib/node_modules/verdaccio-openid/dist/server/index.js:430:17)
verdaccio-desa  |     at authorize (/usr/local/lib/node_modules/verdaccio-openid/dist/server/index.js:300:33)
verdaccio-desa  |     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/verdaccio/node_modules/express/lib/router/layer.js:95:5)
verdaccio-desa  |     at next (/usr/local/lib/node_modules/verdaccio/node_modules/express/lib/router/route.js:149:13)
verdaccio-desa  |     at Route.dispatch (/usr/local/lib/node_modules/verdaccio/node_modules/express/lib/router/route.js:119:3)
verdaccio-desa  |     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/verdaccio/node_modules/express/lib/router/layer.js:95:5)
verdaccio-desa  |     at /usr/local/lib/node_modules/verdaccio/node_modules/express/lib/router/index.js:284:15
verdaccio-desa  |     at param (/usr/local/lib/node_modules/verdaccio/node_modules/express/lib/router/index.js:365:14)
verdaccio-desa  |     at param (/usr/local/lib/node_modules/verdaccio/node_modules/express/lib/router/index.js:376:14)
verdaccio-desa  | http <-- 500, user: null(...), req: 'GET /-/oauth/authorize', error: internal server error
verdaccio-desa  | http <-- 500, user: null(...), req: 'GET /-/oauth/authorize', error: internal server error
verdaccio-desa  | info <-- 10.222.1.42 requested 'GET /-/oauth/callback'
verdaccio-desa  | http <-- 200, user: null(...), req: 'GET /-/oauth/callback', bytes: 0/0
verdaccio-desa  | error--- auth error: Client has not yet been discovered
```
